name: graphrag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - networkx
  - plotly
  - requests
  - beautifulsoup4
  - jupyter
  - pip
  - pip:
    - neo4j==5.15.0
    - langchain==0.1.0
    - langchain-community==0.0.10
    - langchain-openai==0.0.5
    - openai==1.3.7
    - python-dotenv==1.0.0
    - streamlit==1.29.0
    - arxiv==2.1.0
    - scholarly==1.7.11
    - py2neo==2021.2.4
    - transformers==4.36.2
    - torch==2.1.2
    - sentence-transformers==2.2.2
    - faiss-cpu==1.7.4
    - tiktoken==0.5.2
    - pydantic==2.5.2
    - mypy==1.8.0
    - typeguard==4.0.0 